//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPCTrainco.Umbraco.Extensions
{
    using System;
    using System.Collections.Generic;
    
    public partial class API_Log
    {
        public int Seq { get; set; }
        public string Api_request { get; set; }
        public string Api_response { get; set; }
        public Nullable<System.DateTime> Processed_Date { get; set; }
    }
}
