//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPCTrainco.Umbraco.Extensions
{
    using System;
    using System.Collections.Generic;
    
    public partial class Arlo_Rejected_Courses
    {
        public int ID { get; set; }
        public string EventCode { get; set; }
        public Nullable<int> SessionID { get; set; }
        public string CourseTitle { get; set; }
        public string Reason { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    }
}
